[build]
# Use go run instead of go build
cmd = "go run main.go"

# Which directory to watch for changes
include = ["."]

# Directories to exclude from being watched
exclude = ["assets", "tmp", "vendor"]

[logger]
# Log level (default is 'info')
level = "info"
